[project]
name = "kafka-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiokafka>=0.12.0",
    "fastapi>=0.121.0",
    "pydantic>=2.12.4",
    "uvicorn>=0.38.0",
]
